In [ ]:
################################################################################
# Author: Joachim Rath
# MatNr: 
# Description: Live Programming 2024 Task: Student life
# Comments: 
#           
################################################################################

In [1]:
# Your code goes here:
class Activity:
    def __init__(self, name:str, hours:int, required_items:set[str]):
        self.name = name
        self.hours = hours
        self.required_items = required_items

    def __str__(self) -> str:
        return f"{self.name} for ({self.hours} hours)"

class ActivityExecutionError(Exception):
    pass

class Student:
    def __init__(self, number:str, backpack_content:set[str]):
        self.number = number
        self.backpack_content = backpack_content
        self.activity_log = []


    @property
    def number(self) -> str:
        return self._number
    
    @number.setter
    def number(self, number:str):
        if not number.isnumeric():
            raise NameError("Student number is not numeric!")
        else:
            self._number = number
    
    @property
    def spare_time(self):
        total = 0
        for activity in self.activity_log:
            total += activity.hours
        return 24 - total
    
    def all_items_packed(self, activity:Activity):
        return activity.required_items.issubset(self.backpack_content)
    
    def enough_time_left(self, activity:Activity):
        if self.spare_time >= activity.hours:
            return True
        else:
            return False
        
    def execute(self, activity:Activity):
        if not self.enough_time_left(activity):
            raise ActivityExecutionError("The day is over!")
        if not self.all_items_packed(activity):
            raise ActivityExecutionError(f"Not all items available for {activity.name}!")
        self.activity_log.append(activity)

    def live_day(self, todo:list[Activity]):
        for to in todo:
            try:
                self.execute(to)
                print(f"{self.number} executed {to}. Spare time left: {self.spare_time} hours.")
            except ActivityExecutionError as error:
                print(f"{self.number} can not execute {to}!")
                print(error)
                return
        

In [2]:
# Test your code here

print("---------------------------- First  Student ----------------------------")

# TODO: Create a new activity "Sleeping" with a duration of 8 hours and the required items of "Bed"
sleeping = Activity("Sleeping", 8, {"Bed"})
print(sleeping)
# TODO: Create a new activity "Studying" with a duration of 12 hours and the required items of "Teaching materials" and "Discipline"
studying = Activity("Studying", 12, {"Teaching materials", "Discipline"})
# Create a new activity "Spikeball" with a duration of 2 hours and the required items of "Net" and "Ball"
spikeball = Activity("Spikeball", 2, {"Ball", "Net"})

motivated_student = Student("22013847", {"Bed", "Teaching materials", "Discipline", "Ball",  "Net", "Coffee"})

activities = [sleeping, studying, spikeball]
# TODO: Call the live_day method of the student with a list of the activities
motivated_student.live_day(activities)


print("\n---------------------------- Second Student ----------------------------")
not_so_motivated_student = Student("22013848", {"Bed", "Old exams", "Ball",  "Net", "Beer"})
# Create a new activity "Flunkyball" with a duration of 6 hours and the required items of "Ball" and "Beer"
flunkyball = Activity("Flunkyball", 6, {"Ball", "Beer"})
# Create a new activity "Sloppy studying" with a duration of 9 hours and the required items of "Old exams"
sloppy_studying = Activity("Sloppy studying", 9, {"Old exams"})

activities = [sleeping, spikeball, flunkyball, sloppy_studying]

# TODO: Call the live_day method of the student with a list of the activities
not_so_motivated_student.live_day(activities)


# TODO: Create an Activity "Cheating" that requires the item "Cheat sheet"
cheating = Activity("Cheating", 1, {"Cheat sheet"})

# improvise adapt overcome
activities = [cheating]

# TODO: Call the live_day method of the student again
not_so_motivated_student.live_day(activities)

---------------------------- First  Student ----------------------------
Sleeping for (8 hours)
22013847 executed Sleeping for (8 hours). Spare time left: 16 hours.
22013847 executed Studying for (12 hours). Spare time left: 4 hours.
22013847 executed Spikeball for (2 hours). Spare time left: 2 hours.

---------------------------- Second Student ----------------------------
22013848 executed Sleeping for (8 hours). Spare time left: 16 hours.
22013848 executed Spikeball for (2 hours). Spare time left: 14 hours.
22013848 executed Flunkyball for (6 hours). Spare time left: 8 hours.
22013848 can not execute Sloppy studying for (9 hours)!
The day is over!
22013848 can not execute Cheating for (1 hours)!
Not all items available for Cheating!


## Test your classes:
To simplify the validation of your solution, we already provide a small example output, which should be printed by the code in the test cell above. 

```
---------------------------- First  Student ----------------------------
Sleeping for (8 hours)
22013847 executed Sleeping for (8 hours). Spare time left: 16 hours.
22013847 executed Studying for (12 hours). Spare time left: 4 hours.
22013847 executed Spikeball for (2 hours). Spare time left: 2 hours.

---------------------------- Second Student ----------------------------
22013848 executed Sleeping for (8 hours). Spare time left: 16 hours.
22013848 executed Spikeball for (2 hours). Spare time left: 14 hours.
22013848 executed Flunkyball for (6 hours). Spare time left: 8 hours.
22013848 can not execute Sloppy studying for (9 hours)!
The day is over!
22013848 can not execute Cheating for (1 hours)!
Not all items available for Cheating!
```